name: haru-speak-deploy-to-ec2

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Java Spring Gradle
      - uses: actions/checkout@v3
      
      - name: Spring - Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      
      # switch env file 추후 작성 예정
        
      - name: Spring-application build
        run: ./gradlew build
      

      # Docker
      - name: Docker - build image
        run: docker build -t hankwanjin/haru-speak:latest .

      - name: Docker - Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Docker - Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./be/docker
          push: true
          tags: hankwanjin/haru-speak:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Depoly in AWS ec2 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
            sudo docker pull hankwanjin/haru-speak:latest
            sudo docker stop haru-speak-server && sudo docker rm haru-speak-server
            sudo docker run -d --name haru-speak-server -e MYSQL_HOST=${{ secrets.MYSQL_HOST }} -e MYSQL_USERNAME=${{ secrets.MYSQL_USERNAME }} -e MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} -p 8080:8080 hankwanjin/haru-speak:latest
            sleep 60
            sudo docker inspect -f {{.State.Pid}} haru-speak-server | grep -v '^0'
