name: haru-speak-deploy-to-ec2

on:
  push:
    branches: [ main ]
  
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./be
    
    steps:
      # Java Spring Gradle
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SUBMODULE_KEY }}
          submodules: true

      # Update references
      - name: Git Sumbodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
            
      - name: Spring - Setup JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
      
      # switch env file 추후 작성 예정
      
      - name: Spring - Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Spring-application build 
        run: ./gradlew build
      

       # Docker
      - name: Docker - Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker - Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Docker - Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./be
          push: true
          tags: hankwanjin/haru-speak:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Depoly in AWS ec2 
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: | 
            sudo docker system prune -f
            sudo docker pull hankwanjin/haru-speak:latest
            sudo docker stop haru-speak-server && sudo docker rm haru-speak-server
            sudo docker run -d --name haru-speak-server -p 8080:8080 hankwanjin/haru-speak:latest
            sleep 60
            sudo docker inspect -f {{.State.Pid}} haru-speak-server | grep -v '^0'
